version: '3.9'

services:
  bot:
    build: .
    container_name: vpn_bot
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: python main.py
    environment:
      - POSTGRES_DSN=postgresql+asyncpg://vpn_user:vpn_pass@db:5432/vpn_db

  db:
    image: postgres:15
    container_name: vpn_db
    restart: always
    environment:
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_user
      POSTGRES_PASSWORD: vpn_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
